function [after_cr_im,after_cr_re,selected_sample_i,selected_sample_q, selected_sample_valid, strobe] = importChipscopeCSV_v2(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors (If no startrow is given, it is assumed that data starts on row 2).
%   [AFTER_CR_IM1,AFTER_CR_RE1,SELECTED_SAMPLE_I130,SELECTED_SAMPLE_Q130] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [AFTER_CR_IM1,AFTER_CR_RE1,SELECTED_SAMPLE_I130,SELECTED_SAMPLE_Q130] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [after_cr_im1,after_cr_re1,selected_sample_i130,selected_sample_q130] = importfile('unlocked_carrier_clock_success.csv',1, 16385);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/02/21 18:05:17

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column4: text (%s)
%	column6: text (%s)
%   column13: text (%s)
%	column14: text (%s)
%   column27: text (%s)
%	column29: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%*s%s%*s%s%*s%*s%*s%*s%*s%*s%s%s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%s%*s%s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
after_cr_im130_tmp = dataArray{:, 1};
after_cr_re130_tmp = dataArray{:, 2};
selected_sample_i130_tmp = dataArray{:, 3};
selected_sample_q130_tmp = dataArray{:, 4};
selected_sample_valid_tmp = dataArray{:, 5};
strobe_tmp = dataArray{:, 6};

hex_bits = 16;
total_bits = 14;
frac_bits  = 11;

q_int = quantizer('mode', 'ufixed', [hex_bits, 0]);
q_frac = quantizer('mode', 'fixed', [total_bits, frac_bits]);

%after_cr_im130_tmp = after_cr_im130_tmp(2:length(after_cr_im130_tmp));
%after_cr_re130_tmp = after_cr_re130_tmp(2:length(after_cr_re130_tmp));
%selected_sample_i130_tmp = selected_sample_i130_tmp(2:length(selected_sample_i130_tmp));
%selected_sample_q130_tmp = selected_sample_q130_tmp(2:length(selected_sample_q130_tmp));

for i = 1:length(after_cr_im130_tmp)
    after_cr_im(i) = bin2num(q_frac, num2bin(q_int, hex2dec(after_cr_im130_tmp(i))));
    after_cr_re(i) = bin2num(q_frac, num2bin(q_int, hex2dec(after_cr_re130_tmp(i))));
    selected_sample_i(i) = bin2num(q_frac, num2bin(q_int, hex2dec(selected_sample_i130_tmp(i))));
    selected_sample_q(i) = bin2num(q_frac, num2bin(q_int, hex2dec(selected_sample_q130_tmp(i))));
    selected_sample_valid(i) = str2num(selected_sample_valid_tmp{i});
    strobe(i) = str2num(strobe_tmp{i});
    disp(num2str(i))
end


