function [bladeRF_re, bladeRF_im] = importbladeRF_rx(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [BLADERF_RE, BLADERF_IM] = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [BLADERF_RE, BLADERF_IM] = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [bladeRF_re, bladeRF_im] = importfile("/Users/cyarp/git/cyclopsbb-2020/baseband_rev1/bladeRF_rx.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Nov-2021 16:48:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["bladeRF_re", "bladeRF_im"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
bladeRF_re = tbl.bladeRF_re;
bladeRF_im = tbl.bladeRF_im;
end